main:
  - name: Posts
    pageRef: /posts
    weight: 10
    params:
      icon: posts

  - name: Series
    pageRef: /series
    weight: 20
    params:
      icon: series

  - name: Categories
    pageRef: /categories
    weight: 30
    params:
      icon: categories

  - name: More
    weight: 40
    params:
      icon: layers

  - name: Tags
    pageRef: /tags
    weight: 10
    parent: More
    params:
      icon: tags

  - name: Archives
    pageRef: /archives
    weight: 20
    parent: More
    params:
      icon: archive

  - name: About
    pageRef: /about
    weight: 40
    parent: More
    params:
      icon: about

footer:
  - name: About
    pageRef: /about
    weight: 10
    params:
      icon: about

  - name: Contact
    url: mailto:svenvanginkel@icloud.com
    weight: 20
    params:
      icon: contact

  - name: Resume
    pageRef: /resume
    weight: 30
    params:
      icon: file-text

  - name: RSS Feed
    url: /index.xml
    weight: 40
    params:
      icon: rss

social:
  - name: GitHub
    url: https://github.com/svenvg93
    weight: 10
    params:
      icon: github
  - name: X
    url: https://x.com/svenvginkel
    weight: 20
    params:
      icon: twitter
  - name: LinkedIn
    url: https://linkedin.com/in/svenvanginkel
    weight: 30
    params:
      icon: linkedin
