// Add removed post URLs here to return HTTP 410 Gone.
// Use site-relative paths, for example: "/posts/my-old-post/".
export const gonePaths = new Set([
  "/categories/analytics/index.xml/",
  "/categories/logging/",
  "/categories/self-hosting/",
  "/posts/configure-split-dns-with-tailscale-and-local-dns/",
  "/posts/connecting-selfhosted-apps-to-tailscale-with-tsdproxy/",
  "/posts/deploy-zensical-on-cloudflare-workers/",
  "/posts/host-container-monitoring-with-prometheus/",
  "/posts/how-i-use-github-actions-to-update-my-blog-daily/",
  "/posts/jekyll-chirpy-blog-on-cloudflare-pages/",
  "/posts/log-monitoring-with-loki-promtail/",
  "/posts/managing-portainer-stacks-using-gitops/",
  "/posts/material-for-mkdocs-on-cloudflare-pages/",
  "/posts/self-hosting-securely-with-cloudflare-tunnels/",
  "/posts/selfhost-a-single-sign-on-mfa-with-authentik/",
  "/posts/selfhost-your-website-analytics-with-umami/",
  "/posts/secure-your-cloudflare-tunnel-with-authentik/",
  "/posts/secure-your-homelab-with-tailscale-cloudflare/",
  "/posts/setting-up-an-mikrotik-router/",
  "/posts/setting-up-vyos-router-for-your-home-network/",
  "/posts/setting-up-your-travel-router-secure-and-reliable-internet-anywhere/",
  "/posts/setup-ntfy-for-selfhosted-notifications/",
  "/posts/smokeping-essentials-cdn-targets/",
  "/posts/smokeping-essentials-setup/",
  "/posts/smokeping-essentials-the-right-targets/",
  "/posts/wildcard-ssl-certificates-with-traefik-and-unifi-local-dns/",
  "/projects/ookla-server-explorer/",
  "/tags/chirpy/",
  "/tags/cloudflare-tunnel/",
  "/tags/cloudflare-worker/",
  "/tags/linux/",
  "/tags/ntfy/",
  "/tags/umami/",
]);
