name: Check of Broken Links

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-links:
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Run Hugo Link Checker
        uses: marccampbell/hugo-linkcheck-action@v0.1.3